name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.2.2

    steps:
      - uses: actions/checkout@v4

      - run: swift --version

      - run: swift sdk install https://download.swift.org/swift-6.2.2-release/wasm-sdk/swift-6.2.2-RELEASE/swift-6.2.2-RELEASE_wasm.artifactbundle.tar.gz --checksum 128fa003e0cad624897c2b1d5f07cedf400e3c8bd851d304e57440b591cbe606

      - run: swift build --swift-sdk swift-6.2.2-RELEASE_wasm
